---
- hosts: all
  become_user: root
  become: true

  tasks:
     - name: checking the status of kafka
       service_facts:
     
     - debug:
         msg:
           - " kafka service is {{ ansible_facts.services['confluent-kafka-connect.service'].state }}"
       when: inventory_hostname == 'workernode2.testlab.com'
       
  #   - name: upgrade all packages, excluding docker, kernel, httpd, mysql, apache, java, percona, tomcat related packages
  #     become: true
  #     yum:
  #       name: '*'
  #      state: latest
  #     exclude: '*mongo* java* kafka* *docker*rpcbind* runc* container* iptables*'
      
     - name: rebooting the servers
       reboot:
         reboot_timeout: 3600
       become: true

     - name: waiting for host to finish reboot
       wait_for:
         port: "{{ (ansible_port|default(ansible_ssh_port))|default(22) }}"
         host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
         search_regex: OpenSSH
         delay: 10
         connection: local
      
     - name: checking the status of confluent kafka connect
       service_facts:

     - debug:
          msg:
            - " kafka service is {{ ansible_facts.services['confluent-kafka-connect.service'].state }}"

 

