---
- hosts: localhost
  tasks:
    - name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
      uri:
        url: http://10.251.172.94:9021
        return_content: yes
      register: this
      #failed_when: "'AWESOME' not in this.content"
    - debug: msg="{{ this.status }}"
