---
- hosts: web
  become_user: root

  tasks:
    - name: inspecting docker swarm
      shell: docker node ls
      register: swarm_info
      no_log: yes
      become: true
      ignore_errors: yes

    - debug:
        msg:
          - "{{ swarm_info.stdout_lines }}"
          - "{{ swarm_info.stdout_lines.1.split()[2] }} is Leader"
          
    - set_fact:
        leader: "{{ swarm_info.stdout_lines.1.split()[2] }}"
        

    - name: checking swarm status
      shell: 'docker info | grep Swarm'
      register: swarm_stat
      delegate_to: "{{ leader }}"
      become: true
      
    - debug: msg=" docker swarm is {{ swarm_stat.stdout_lines.0.split()[1] }}"
    
    - name: stopping docker service
      shell: systemctl stop docker
      become: true
      register: docker_status
      delegate_to: "{{ item }}"
      when: "( item != leader )"
      with_inventory_hostnames:
        - all
    - include: print.yml

    - include: reboot.yml
#      delegate_to: "{{ item }}"
#      when: "( item != leader )"
#      with_inventory_hostnames:
#        - all
